using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging.Abstractions;
using NSubstitute;
using NickButlerAdroit.Api.Exceptions;
using NickButlerAdroit.Api.Hubs;
using NickButlerAdroit.Api.Repositories;
using NickButlerAdroit.Api.Services;

namespace NickButlerAdroit.Tests.Unit;

public class UrlShortenerServiceConcurrencyTests
{
    private readonly UrlShortenerService _service;
    private readonly InMemoryUrlRepository _repo;

    public UrlShortenerServiceConcurrencyTests()
    {
        _repo = new InMemoryUrlRepository();
        var hubContext = Substitute.For<IHubContext<UrlHub>>();
        var clients = Substitute.For<IHubClients>();
        var clientProxy = Substitute.For<IClientProxy>();
        clients.All.Returns(clientProxy);
        hubContext.Clients.Returns(clients);
        _service = new UrlShortenerService(_repo, hubContext, NullLogger<UrlShortenerService>.Instance);
    }

    [Fact]
    public async Task CreateAsync_ConcurrentAutoGenerated_AllProduceUniqueShortCodes()
    {
        const int count = 50;

        var tasks = Enumerable.Range(0, count)
            .Select(i => _service.CreateAsync($"https://example.com/{i}"))
            .ToArray();

        var results = await Task.WhenAll(tasks);

        var shortCodes = results.Select(r => r.ShortCode).ToList();
        Assert.Equal(count, shortCodes.Distinct().Count());
        Assert.All(results, r => Assert.Equal(7, r.ShortCode.Length));
    }

    [Fact]
    public async Task CreateAsync_ConcurrentSameCustomCode_ExactlyOneWins()
    {
        const int count = 20;

        var tasks = Enumerable.Range(0, count)
            .Select(i => _service.CreateAsync($"https://example.com/{i}", "racecode"))
            .ToArray();

        var settled = await Task.WhenAll(
            tasks.Select(async t =>
            {
                try
                {
                    await t;
                    return (Succeeded: true, WasDuplicate: false);
                }
                catch (DuplicateShortCodeException)
                {
                    return (Succeeded: false, WasDuplicate: true);
                }
            })
        );

        var successes = settled.Count(s => s.Succeeded);
        var duplicates = settled.Count(s => s.WasDuplicate);

        Assert.Equal(1, successes);
        Assert.Equal(count - 1, duplicates);
    }

    [Fact]
    public async Task DeleteAsync_ConcurrentDeletesOfSameCode_ExactlyOneSucceeds()
    {
        await _service.CreateAsync("https://example.com", "delrace");
        const int count = 20;

        var settled = await Task.WhenAll(
            Enumerable.Range(0, count).Select(async _ =>
            {
                try
                {
                    await _service.DeleteAsync("delrace");
                    return true;
                }
                catch (KeyNotFoundException)
                {
                    return false;
                }
            })
        );

        Assert.Equal(1, settled.Count(s => s));
        Assert.Equal(count - 1, settled.Count(s => !s));
    }

    [Fact]
    public async Task ResolveForRedirectAsync_ConcurrentClicks_AllCounted()
    {
        await _service.CreateAsync("https://example.com", "clicks");
        const int count = 200;

        var tasks = Enumerable.Range(0, count)
            .Select(_ => _service.ResolveForRedirectAsync("clicks"))
            .ToArray();

        await Task.WhenAll(tasks);

        var stats = await _service.GetStatsAsync("clicks");
        Assert.Equal(count, stats.ClickCount);
    }

    [Fact]
    public async Task ResolveAsync_ConcurrentClicks_AllCounted()
    {
        await _service.CreateAsync("https://example.com", "apiclk");
        const int count = 200;

        var tasks = Enumerable.Range(0, count)
            .Select(_ => _service.ResolveAsync("apiclk"))
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Each resolve returns an incrementing click count, all should be unique
        var clickCounts = results.Select(r => r.ClickCount).ToList();
        Assert.Equal(count, clickCounts.Distinct().Count());

        var stats = await _service.GetStatsAsync("apiclk");
        Assert.Equal(count, stats.ClickCount);
    }

    [Fact]
    public async Task ConcurrentCreatesAndDeletes_DoNotThrowUnexpectedExceptions()
    {
        // Pre-create entries that will be targets for deletion
        for (var i = 0; i < 20; i++)
        {
            await _service.CreateAsync($"https://example.com/pre-{i}", $"cdmix{i:D4}");
        }

        // Concurrently create new entries and delete existing ones
        var createTasks = Enumerable.Range(0, 20)
            .Select(i => _service.CreateAsync($"https://example.com/new-{i}"));
        var deleteTasks = Enumerable.Range(0, 20)
            .Select(i => SafeDelete($"cdmix{i:D4}"));

        await Task.WhenAll(createTasks.Concat(deleteTasks));

        // State should be consistent — all remaining entries are retrievable
        var all = await _service.GetAllAsync();
        foreach (var entry in all)
        {
            var resolved = await _service.GetStatsAsync(entry.ShortCode);
            Assert.NotNull(resolved);
        }
    }

    private async Task SafeDelete(string shortCode)
    {
        try
        {
            await _service.DeleteAsync(shortCode);
        }
        catch (KeyNotFoundException)
        {
            // Expected if another thread deleted it first
        }
    }
}
