using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using NickButlerAdroit.Api.Models;

namespace NickButlerAdroit.Tests.Integration;

public class ConcurrencyIntegrationTests : IClassFixture<NoRateLimitWebApplicationFactory>
{
    private readonly NoRateLimitWebApplicationFactory _factory;

    public ConcurrencyIntegrationTests(NoRateLimitWebApplicationFactory factory)
    {
        _factory = factory;
    }

    [Fact]
    public async Task Post_ConcurrentAutoGeneratedUrls_AllReturn201WithUniqueShortCodes()
    {
        var client = _factory.WithWebHostBuilder(_ => { }).CreateClient();
        const int count = 10;

        var tasks = Enumerable.Range(0, count)
            .Select(i => client.PostAsJsonAsync("/api/urls", new CreateUrlRequest($"https://example.com/int-conc-{i}")))
            .ToArray();

        var responses = await Task.WhenAll(tasks);

        var shortCodes = new List<string>();
        foreach (var response in responses)
        {
            Assert.Equal(HttpStatusCode.Created, response.StatusCode);
            var result = await response.Content.ReadFromJsonAsync<ShortUrlResult>();
            Assert.NotNull(result);
            shortCodes.Add(result.ShortCode);
        }

        Assert.Equal(count, shortCodes.Distinct().Count());
    }

    [Fact]
    public async Task Post_ConcurrentSameCustomCode_ExactlyOneCreated()
    {
        var client = _factory.WithWebHostBuilder(_ => { }).CreateClient();
        var alias = $"crace{DateTime.UtcNow.Ticks % 100000:D5}";
        const int count = 10;

        var tasks = Enumerable.Range(0, count)
            .Select(i => client.PostAsJsonAsync("/api/urls", new CreateUrlRequest($"https://example.com/race-{i}", alias)))
            .ToArray();

        var responses = await Task.WhenAll(tasks);
        var statuses = responses.Select(r => r.StatusCode).ToList();

        Assert.Equal(1, statuses.Count(s => s == HttpStatusCode.Created));
        Assert.Equal(count - 1, statuses.Count(s => s == HttpStatusCode.Conflict));
    }

    [Fact]
    public async Task Delete_ConcurrentDeletesOfSameCode_ExactlyOneSucceeds()
    {
        var client = _factory.WithWebHostBuilder(_ => { }).CreateClient();
        var alias = $"cdel0{DateTime.UtcNow.Ticks % 100000:D5}";

        var createResponse = await client.PostAsJsonAsync("/api/urls", new CreateUrlRequest("https://example.com/del-target", alias));
        Assert.Equal(HttpStatusCode.Created, createResponse.StatusCode);

        const int count = 10;

        var tasks = Enumerable.Range(0, count)
            .Select(_ => client.DeleteAsync($"/api/urls/{alias}"))
            .ToArray();

        var responses = await Task.WhenAll(tasks);
        var statuses = responses.Select(r => r.StatusCode).ToList();

        Assert.Equal(1, statuses.Count(s => s == HttpStatusCode.OK));
        Assert.Equal(count - 1, statuses.Count(s => s == HttpStatusCode.NotFound));
    }

    [Fact]
    public async Task Redirect_ConcurrentClicks_AllCountedAtomically()
    {
        var client = _factory.WithWebHostBuilder(_ => { }).CreateClient(
            new WebApplicationFactoryClientOptions { AllowAutoRedirect = false });
        var alias = $"cclk0{DateTime.UtcNow.Ticks % 100000:D5}";

        await client.PostAsJsonAsync("/api/urls", new CreateUrlRequest("https://example.com/click-target", alias));

        const int clickCount = 20;

        var tasks = Enumerable.Range(0, clickCount)
            .Select(_ => client.GetAsync($"/{alias}"))
            .ToArray();

        var responses = await Task.WhenAll(tasks);

        foreach (var response in responses)
        {
            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
        }

        // Verify all clicks were counted via the stats endpoint
        var statsResponse = await client.GetAsync($"/api/urls/{alias}/stats");
        Assert.Equal(HttpStatusCode.OK, statsResponse.StatusCode);
        var stats = await statsResponse.Content.ReadFromJsonAsync<UrlStats>();
        Assert.NotNull(stats);
        Assert.Equal(clickCount, stats.ClickCount);
    }
}
